[package]
name = "ytm-audio"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
ytm-source = { path = "../ytm-source" }
anyhow.workspace = true
tokio.workspace = true
reqwest.workspace = true
tracing.workspace = true
serde.workspace = true
dirs = "6"
rodio = { version = "0.22", default-features = false, features = ["playback", "mp4"] }
